### PR TITLE
Added Expert Parameters

### PR DESCRIPTION
**Pull request by binarybucks**
Parameters that are available in the Smartset "Fachmann" Menu were not pulled before. 
This PR adds those parameter IDs to the list of queried parameters to provide much more information, most importantly the energy statistics that are weirdly not available as a normal user. 

In my testing, it seems that the "Fachmann-Passwort" (default 1111) via a GET call to `api/portal/ExpertLogin` is not required to pull the values via the API. The Smartset app also displays some of these expert values without an additional password. 

Values now returned by my CHA07 heatpump with ism7i (Wolflink Home)
```
% ISM DHCP Active False
% ISM IP address XXX
% ISM Subnet mask XXX
% ISM Default gateway XXX
% ISM DNS name server XXX
% ISM WLAN active False
% ISM System name WolfLink
% ISM ISM serial number XXX
% ISM ISM software version 3.00.412
% ISM ISM hardware version 3.0
% ISM Enable internet connection True
% ISM LAN MAC address XXX
% ISM WLAN MAC address 000000000000
% System parameters Room influence factor 4
% System parameters Outside sensor averaging time 3
% System parameters Adjustment room sensor BM-2 0 0
% System parameters Pasteurisation function 0
% System parameters Maintenance message 0
% System parameters Enable parallel mode 0
% System parameters Room temperature-dependent shutdown 0
% System parameters Setback stop 0
% System parameters Minimum DHW temperature 47
% System parameters Outside temperature correction -5
% System parameters Room temperature PI controller Kp 20
% System parameters Room temperature PI controller Tn 1
% System parameters Pasteurisation function start time 18:00
% System parameters Program selector common 1
% System parameters Activation SmartHome 1
% Settings and displays Programming unit function 0
% Settings and displays Outside temperature 9.3
% Settings and displays Time 10:12
% Settings and displays Date 28.10.2024
% Settings and displays Firmware 3.2
% SmartHome info SmartHome System 0
% Direct heating circuit Set value correction 0
% Direct heating circuit Day temperature 20
% Direct heating circuit Average outside temperature 8.5
% Direct heating circuit Flow temperature 32.4
% Direct heating circuit Heating circuit demand 7
% Direct heating circuit Heating circuit status 1
% Direct heating circuit Economy factor 0
% Direct heating circuit Winter/summer changeover 15
% Direct heating circuit ECO/ABS 9
% Direct heating circuit Room influence 0
% Direct heating circuit Heating curve low end temperature 25
% Direct heating circuit Heating curve starting point 15
% Direct heating circuit Standard outside temperature for heating curve -11
% Direct heating circuit Flow temperature for heating curve 40
% invisible controller type 1
% Settings and displays Operating mode heater 10
% Settings and displays compressor status 5
% Settings and displays Electric booster heater status 11
% Settings and displays Status of additional heat generator 1
% Settings and displays Set boiler temperature 28.8
% Settings and displays Boiler temperature 2 31.26
% Settings and displays Set DHW temperature 10
% Settings and displays Supply air temperature 7.7
% Settings and displays Extract air temp 6.2
% Settings and displays suction gas temperature 9.1
% Settings and displays Heißgastemperatur 43.8
% Settings and displays P_hot gas 11.1
% Settings and displays P_intake gas 5.5
% Settings and displays EEV HTG 153
% Settings and displays EEV C 0
% Settings and displays Rotation speed ZHP 60
% Settings and displays E-heating phase 1 0
% Settings and displays Electric heating phase 2 and 3 0
% Settings and displays Current capacity specification Compressor 15
% Settings and displays Compressor 1
% Settings and displays Fan speed 440
% Settings and displays Status night operation 0
% Settings and displays DPM status 65088
% Settings and displays SG status 0
% Settings and displays PV status 1
% Settings and displays Input E1 65088
% Settings and displays Input E3 65088
% Settings and displays Input E4 65088
% Settings and displays Output A1 0
% Settings and displays Output A3 0
% Settings and displays Output A4 0
% Settings and displays Power consumption (WP + EHZ) 0.4
% Settings and displays Current secondary power 3.2
% Settings and displays Heating output 3.1
% Settings and displays Cooling capacity 0
% Settings and displays Hours with mains power on 10454
% Settings and displays Compressor operating hours 4075
% Settings and displays E-Heating operating hours 0
% Settings and displays Number Power On 26
% Settings and displays compressor starts 749
% Settings and displays HCM-4 firmware 1.6
% Settings and displays HPM-2 firmware 2
% Settings and displays Output category 7
% Settings and displays T_boiler correction 0
% Settings and displays T_boiler_2 correction -0.17
% Settings and displays T_return correction -0.09
% Settings and displays manufacturing week 29
% Settings and displays year of manufacture 23
% Settings and displays Serial number 659440
% Settings and displays DHW operating mode 0
% Settings and displays Operating mode compressor 0
% Statistics Energy amount HTG 11174
% Statistics Energy amount DHW 1764
% Statistics Clg energy amount 0
% Statistics Consumption current day 0
% Statistics Heat generated current day 0
% Statistics Consumption previous day 7
% Statistics Heat generated previous day 45
% Statistics DPF previous day 6.4
% Statistics Consumption current month 169
% Statistics Heat generated current month 898
% Statistics Consumption current year 1820
% Statistics Heat generated current year 7686
% Statistics SPF current year 4.2
% Statistics Consumption previous year 1169
% Statistics Heat generated previous year 5252
% Statistics SPF previous year 4.5
% Statistics Consumption year before last 0
% Statistics Heat generated year before last 0
% DHW DHW temperature 46.2
% DHW 1x DHW 0
% Common settings Set DHW temperature, adjusted 48
% Common settings Prog. select. 1
% DHW DHW status 9
% DHW Time program 1
% Heat generator 1 Boiler water temperature 32.4
% Heat generator 1 Return temperature 29.4
% Heat generator 1 HC flow rate 16.4
% Heat generator 1 System pressure 1.76
% Heat generator 1 Heating circuit pump 1
% Heat generator 1 Feed/heating circuit pump 1
% Heat generator 1 3-way diverter valve HTG/DHW 0
% Heat generator 1 3-way diverter valve HTG/CLG 0
% Heat generator 1 Electric booster heater 0
% Direct heating circuit Party mode 0
% Direct heating circuit Holiday mode 0
% Common settings Set value correction 0
% Direct heating circuit Time program 3
% Compressor frequency 25
```

Feel free to suggest any improvements or let me know if there was a reason to not pull the expert parametes previously :)

### CODE REVIEW

**Comment by mtielen** [comment]
Thanks @binarybucks I think would be good to make the Expert values options. Also looking at it I think we should create different devices elements as Wolf uses instead of the recently introduced Grouping. So like create an ISM device and then list the parameters  or BM2 or CHA07 etc etc. I feel the overview will be a long list. Currently I'm looking at creating changable entities based on the structures as everything is now just a sensor. What do you think?

**Comment by binarybucks** [comment]
Yeah I found the grouping to be a bit weird but didn't want to break everything. 

What about simply grouping by the corresponding MenuName_TabName? That would result in a rather long list for e.g. benutzer_heizung_parameter1-N, benutzer_warmwasser_parameter1-N, expert_heizgerät_parameter1-N, expert_bm-2_parameter1-N, expert_ism7_parameter1-N making it very clear were which value came from. 

Groups might have to be retained though e.g. to differentiate multiple heating circuits. 
I don't have any, hence I'm unsure how those would be returned by the API. 

While we're at it, can we introduce a Power and Energy Parameter class to assign the correct device classes in Home Assistant?

**Comment by mtielen** [comment]
The groups are taken from the naming you do in Wolfs interface and you can change them there I noticed. So it's not really good mechanics. Technically wouldn't break to change it as HA takes care of it with references. I think grouping by device will probably also solve the issue the Grouping was trying to solve for double parameters this you wouldn't have then either.  I think if we would use the Device Template valuable can group it more logical. Currently it uses your Wolf system name on the portal which the use gave it as Device name.

Yes of course we can introduce Power and Energy Parameters. I just took it over some time ago as the original maintainer stopped maintaining.  All help is welcome!

**Comment by binarybucks** [comment]
Not sure if your `deviceTemplateName` looks different, but that's now my config is looking. 
I don't see a reference between most of the ParameterDescriptors and the deviceTemplateName so I don't think you can group by that either. 
 
```
               "SVGHeatingSchemaConfigDevices":[
                  {
                     "dt":"HG",
                     "di":1,
                     "deviceTemplateName":"CHA",
                     "configIndex":1,
                     "parameters":[
                        {
                           "valueId":27000600001,
                           "unit":"°C",
                           "parameterName":"KF Kesseltemperatur",
                           "parameterId":27000600001
                        },
                        {
                           "valueId":27000900001,
                           "unit":"°C",
                           "parameterName":"RL Rücklauffühler",
                           "parameterId":27000900001
                        },
                        {
                           "valueId":27000700001,
                           "unit":"°C",
                           "parameterName":"SF Speicherfühler",
                           "parameterId":27000700001
                        },
                        {
                           "valueId":27002800001,
                           "unit":"l/min",
                           "parameterName":"DFL Durchflusssensor",
                           "parameterId":27002800001
                        },
                        {
                           "valueId":27003000001,
                           "unit":"bar",
                           "parameterName":"DHK Druck Heizkreis",
                           "parameterId":27003000001
                        },
                        {
                           "valueId":27001200001,
                           "parameterName":"ZHP Zubringer-/Heizkreispumpe",
                           "parameterId":27001200001
                        },
                        {
                           "valueId":27001300001,
                           "parameterName":"3WUV HZ/WW 3-Wege-Umschaltventil",
                           "parameterId":27001300001
                        },
                        {
                           "valueId":27001400001,
                           "parameterName":"3WV HZ/K 3-Wege-Umschaltventil",
                           "parameterId":27001400001
                        },
                        {
                           "valueId":27004800001,
                           "unit":"Hz",
                           "parameterName":"Verdichterfrequenz",
                           "parameterId":27004800001
                        },
                        {
                           "valueId":27001600001,
                           "parameterName":"E-Heizung",
                           "parameterId":27001600001
                        }
                     ]
                  },
                  {
                     "dt":"BM",
                     "di":0,
                     "deviceTemplateName":"BM_2",
                     "configIndex":0
                  },
                  {
                     "dt":"DHK",
                     "di":0,
                     "deviceTemplateName":"DHK_BM_2",
                     "configIndex":0,
                     "hdt":"CHA",
                     "hdi":1
                  },
                  {
                     "dt":"WWSystem",
                     "di":0,
                     "deviceTemplateName":"WWSystem_BM_2",
                     "configIndex":0,
                     "hdt":"CHA",
                     "hdi":1
                  }
               ]

```

There's a `ProtGrp` for some of the parameters e.g. for "HG <1>" for 27005800001 Aktuelle Sekundärleistung. However that is also missing for parameters that are clearly numbered for multiple instances such as 27005900001 Energiemenge HZ  both of which are in `Group` 210_Wärmeerzeuger 1 for my system. 

To me the only sane distinction would really be the parameter's  `group` attribute.

**Comment by mtielen** [comment]
Mine is a bit different as I have a gas system with solar for warmwater.

If I would use the devicetemplatename I would get next to the ISM7 the following grouping:
image

**Comment by mtielen** [comment]
In the Wolf web interface they are not mapped together but in their device tool they are as the Device template is the wolf device which the parmeters belong too. For instance when you change the BM-2 or take it out these parameters connecting to it won't exist anymore same goes with the SM1 in my case which is the Solar module. Collector parameters you won't have in your system as you don't have SM1 device in your setup.

Regards,
Martijn

**Comment by binarybucks** [comment]
yes, but how to you get them via the Smartset API? I don't see /api/portal/GetGuiDescriptionForGateway or any other call that returns those?

**Comment by mtielen** [comment]
Yes it's the same GetGuiDescriptionForGateway it adapts to your configurations (You have different parameters then I as you have a heat pump and I have gasheating with Solar) and the devicetemplatename provides which Wolf Device is giving those parameters like explained before.

**Comment by mtielen** [comment]
I just had a look through my json and I agree for the "fachmann" items we can't use device template here it's much more difficult to do an automatic mapping unless we depending on menu naming. I like your approach on the group element I have some expert values which don't have a group but let's see what happens there they do have this ProtGrp.  with your changes we can start implementing climate entities but also switches based on the write parameter code I have been working on.  Important for that is the "valueId" but would need to know if the parameter is read-only or not, because when it's read-only it's automatically a sensor.

Long answer short yes pls amend it and I will merge it and create a new lib release.

**Comment by binarybucks** [comment]
ok, added in 3e7bcceb4e45e80f13d97d45e68c1a3c4d0d4df7 is a new `fetch_parameters_v2` function. I left the old one intact so you can easily play with the new one without breaking too much. It recursively extracts all items from all `ParameterDescriptors` arrays returned from the messy API response as a single list without depending on the actual structure. 

Duplicates are removed from the list via the existing function. 

I tweaked the `_map_parameter` function to use the group name as parent as none is set in the new fetch_parameters_v2. Not sure if that makes sense but try how it works for you. 

Also added are PowerParameter and EnergyParameter for kW and kWh units.

**Review by mtielen — APPROVED** [review]
Looks good! Thanks.

**Comment by mtielen** [comment]
I had a look it initially looked good but when putting it in home assistant it had some issues and was breaking existing setups also it the list returning from V2 has duplications. Also the name should not contain _ as this causes issues Home assistant does this itself when an entity is created and a name contains _ I have reverted this change and 0.0.19 you can test with. I noticed I don't get values for ISM and some expert parameters they stay on unknown.

**Comment by binarybucks** [comment]
Can you try playing with the following commit? https://github.com/binarybucks/wolf-comm/commit/69a59cad6073b3c37d28645d020f96c85a8f5cb3

I've added an optional local path to fetch_parameters_v2 and fetch_value to save the returned API JSON as local file and use that for testing responses as I hit API limits during testing. It's also nice to have the response as file to compare things. 

Example: 
```
  parameters = await wolf_client.fetch_parameters_v2(XX, XX, "/tmp/wolf/parameters.json")
  values = await wolf_client.fetch_value(XX, XX,parameters, /tmp/wolf/values.json);
```
Also changed :
- Changed the name to use only the name attribute again (and without _). We probably would have to prefix the name with the ValueID to really make it unique as there are parameters with different ValueID but same name (e.g. Programmwahl) for different things. Or leave it as is and let the Home Assistant code create entities with the name and ValueID_name as the entity id. 

- Deduplicate by ValueID in fix_duplicated_parameters
- Temporarily removed skipping parameters with `None` Value in fetch_value to check why values are missing in response like ISM ones. 

The API really is one of the worst I've seen so far. From my testing one has to call fetch_value with the same parameters multiple times to get values for all requested parameters. Sometimes no value is returned, sometimes there is. If you check the browser network requests for wolf-smartset.com it continously polls for values too.

It looks like the expert values are returned from a different system which needs some time and most of normal values are readily available.

**Comment by mtielen** [comment]
Yes it's a terrible API. It's  a lot of reverse engineering also some parameters have dependencies on others which make it even more complex.  

I believe the values are not coming as the BundleId is different it's 7500 on the ISM. On the normal page for me it's 1000. On other items in the expert section I also have different BundleId's.  I don't think the repeating is the issue as the HA integration polls every  60 seconds. Their webpage does it every 10 seconds. The rate limiting by Wolf is not on the api call but on the authentication you need to make sure you keep your session alive. Just make sure you keep renewing your session in time.

**Comment by mtielen** [comment]
I just did a test. I think if we want to add expert parameters we need to start adding the BundleId to the parameters and do a fetch per BundleId to get all the values

**Comment by binarybucks** [comment]
I implemented grouping and fetching by BundleId which indeed results in more values being returned

```
22003200000 Uhrzeit value: 19:45
22003300000 Datum value: 01.11.2024
22003400000 Partymodus value: 0
22003500000 Urlaubsmodus value: 0
22004200000 1x Warmwasser value: 0
22009100000 SmartHome System value: 0
22010400000 Wartungsmeldung value: 0
22010800000 Programmwahlschalter gemeinsam value: 1
27000400001 Kesselsolltemperatur value: 28
27000500001 Außentemperatur value: 11.2
27000600001 KF Kesseltemperatur value: 33.5
27000700001 SF Speicherfühler value: 48.6
27000800001 Warmwassersolltemperatur value: 10
27000900001 RL Rücklauffühler value: 30.7
27001000001 Aktuelle Leistungsvorgabe Verdichter value: 15
27001100001 Heizkreispumpe value: 1
27001200001 ZHP Zubringer-/Heizkreispumpe value: 1
27001300001 3WUV HZ/WW 3-Wege-Umschaltventil value: 0
27001400001 3WV HZ/K 3-Wege-Umschaltventil value: 0
27001500001 Ausgang A1 value: 0
27001600001 E-Heizung value: 0
27001700001 Verdichter value: 1
27001800001 Ausgang A3 value: 0
27001900001 Ausgang A4 value: 0
27002000001 E-Heizung Phase 1 value: 0
27002100001 E-Heizung Phase 2 und 3 value: 0
27002200001 HCM-4 Firmware value: 1.6
27002300001 HPM-2 Firmware value: 2
27002400001 Leistungsklasse value: 7
27002500001 Verdichterstarts value: 762
27002600001 Netzbetriebsstunden value: 10552
27002700001 Betriebsstunden Verdichter value: 4134
27002800001 DFL Durchflusssensor value: 16.5
27003000001 DHK Druck Heizkreis value: 1.78
27003100001 Eingang E1 value: 65088
27003200001 Eingang E3 value: 65088
27003300001 Eingang E4 value: 65088
27003400001 Status TPW value: 65088
27003500001 Drehzahl ZHP value: 60
27003600001 Anzahl Netz Ein value: 26
27003700001 Status SG value: 0
27003800001 Betriebsstunden E-Heizung value: 0
27003900001 Status PV value: 1
27004000001 Zulufttemperatur value: 10
27004100001 Heißgastemperatur value: 44.7
27004200001 Sauggastemperatur value: 9.4
27004300001 Ablufttemperatur value: 7.1
27004400001 Kesseltemperatur 2 value: 32.25
27004500001 Kühlleistung value: 0
27004600001 Heizleistung value: 3
27004700001 Drehzahl Ventilator value: 305
27004800001 Verdichterfrequenz value: 25
27004900001 Leistungsaufnahme (WP + EHZ) value: 0.4
27005000001 Betriebsart Heizgerät value: 10
27005100001 Verdichterstatus value: 5
27005200001 Status E-Heizung value: 11
27005300001 Status Zusatzwärmeerzeuger value: 1
27005500001 Korrektur T_Kessel value: 0
27005600001 Korrektur T_Kessel_2 value: -0.17
27005700001 Korrektur T_Rücklauf value: -0.09
27005800001 Aktuelle Sekundärleistung value: 3.1
27005900001 Energiemenge HZ value: 11325
27006000001 Energiemenge WW value: 1777
27006100001 Energiemenge Kühl. value: 0
27006300001 P_Heißgas value: 11.4
27006400001 P_Sauggas value: 5.5
27006500001 EEV HZ value: 154
27006600001 EEV K value: 0
27014400001 Status Nachtbetrieb value: 0
27014500001 Warmwasser Betriebsart value: 0
27014600001 Betriebsart Verdichter value: 0
27016000001 Verbrauch aktueller Tag value: 1
27016100001 Erzeugte Wärmemenge aktueller Tag value: 0
27016200001 Verbrauch aktueller Monat value: 1
27016300001 Erzeugte Wärmemenge aktueller Monat value: 0
27016400001 Verbrauch aktuelles Jahr value: 1849
27016500001 Erzeugte Wärmemenge aktuelles Jahr value: 7850
27016600001 Verbrauch Vorjahr value: 1169
27016700001 Erzeugte Wärmemenge Vorjahr value: 5252
27016800001 Verbrauch Vorvorjahr value: 0
27016900001 Erzeugte Wärmemenge Vorvorjahr value: 0
27017200001 JAZ aktuelles Jahr value: 4.2
27017300001 JAZ Vorjahr value: 4.5
27017500001 Verbrauch Vortag value: 7
27017600001 Erzeugte Wärmemenge Vortag value: 45
27017700001 TAZ Vortag value: 6.4
27017800001 Herstellwoche value: 29
27017900001 Herstelljahr value: 23
27018000001 Seriennummer value: 659440
34000100000 Gemittelte Außentemperatur value: 10.1
34000400000 Anforderung Heizkreis value: 7
34000500000 Heizkreis Status value: 1
34000600000 Sparfaktor value: 0
34000700000 Winter/Sommer Umschaltung value: 15
34000800000 ECO/ABS value: 9
34000900000 Tagtemperatur value: 20
34001000000 Raumeinfluss value: 0
34001100000 Vorlauftemperatur value: 33.5
34001200000 Sockeltemperatur Heizkurve value: 25
34001300000 Startpunkt Heizkurve value: 15
34001400000 Normaußentemperatur Heizkurve value: -11
34001500000 Vorlauftemperatur Heizkurve value: 40
34001600000 Zeitprogramm value: 3
34002600000 Sollwertkorrektur value: 0
34002900000 Programmwahl value: 1
34003100000 Sollwertkorrektur value: 0
34003200000 Programmwahl value: 1
34003300000 Reglertyp value: 1
34003500000 Tagtemperatur value: 20
34004000000 Tagtemperatur value: 20
35000100000 Warmwasser Status value: 9
35000400000 Zeitprogramm value: 1
35000900000 Warmwassersolltemperatur eingestellt value: 48
35001200000 Programmwahl value: 1
35001400000 Warmwassersolltemperatur eingestellt value: 48
35001500000 Programmwahl value: 1
got 116 values for 213 parameters
```

I'll cleanup the code, check which parameters are missing and push it for you to test

**Comment by mtielen** [comment]
Thanks @binarybucks ! Let's keep the grouping the same as it was using the Group option. The Paramater number is in stored as an attribute already in Homeassistant. Also in Home Assistant integration it creates the unique id. Adding the valueId in the beginning will make also translation difficult and I know that the HA dev want user readable names.

**Pull request merged**
