### PR TITLE
Avoid repeated token retrieval

### PR DESCRIPTION
**Pull request by torkleyy**
Avoids authenticating for every request by checking the token expiration date

### CODE REVIEW

**Comment by GexxOn** [comment]
pls merge

**Comment by mtielen** [comment]
@torkleyy:
I have implemented your code it's not fully fixing the issue. You get more data points but it's still not continues connecting.

**Comment by torkleyy** [comment]
@mtielen okay. It's gonna take me some time until I can look into it.

**Comment by mtielen** [comment]
@torkleyy  I figurred out the issue. The sessionid is expiring as we don't call the update session api every 60 seconds as the website is doing and also what I see in the ioBroker adapter.

**Pull request merged**
